version: '3.8'

networks:
  redmine_net:
     name: redmine-networks

services:
# nginx
  web:
    image: steveltn/https-portal:1
    container_name: web
    restart: always
    volumes:
      - ./web/ssl_certs:/var/lib/https-portal
    networks:
      - redmine_net
    ports:
      - ${HOSTNAME_READMINE}:80:80
      - ${HOSTNAME_READMINE}:443:443
    env_file:
      - .env
    environment:
      DOMAINS: >-
        ${HOSTNAME_READMINE} -> http://redmine:${REDMINE_DOCKER_PORT}/,
      STAGE: 'local'
    depends_on:
      - redmine
      - reddb

# Redmine Apps
  redmine:
    image: redmine:latest
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    volumes:
      - ./app/plugins:/usr/src/redmine/plugins
      - ./app/themes:/usr/src/redmine/public/themes
      - ./app/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ./app/files:/usr/src/redmine/files
    networks:
      - redmine_net
    expose:
      - ${APP_DOCKER_PORT}
    env_file:
      - .env
    environment:
      - REDMINE_DB_POSTGRES=reddb
      - REDMINE_DB_DATABASE=${DB_NAME}
      - REDMINE_DB_USERNAME=${DB_USER}
      - REDMINE_DB_PASSWORD=${DB_PASSWORD}
      - TZ=${DB_TZ}
    depends_on:
      - reddb

# postgreSQL
  reddb:
    image: postgres:latest
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/dbdata:/var/lib/postgresql/data
    networks:
      - redmine_net
    expose:
      - ${DB_DOCKER_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=${DB_TZ}
    command: --port=${DB_DOCKER_PORT}
